name: CI
on: [push]
jobs:
  build:
    runs-on: ubuntu-20.04
#ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: cloudflared tunel
      run: |
        wget https://github.com/cloudflare/cloudflared/releases/latest/download/cloudflared-linux-amd64
        chmod +x cloudflared-linux-amd64
        ./cloudflared-linux-amd64 tunnel&
    - name: Setup tmate session
      uses: mxschmitt/action-tmate@v3
      timeout-minutes : 300
