name:  start workers
on:
  issues:
    types: labeled
jobs:
  build:
    runs-on: ubuntu-18.04
    steps:
    - uses: actions/checkout@v2
    - name: clean space
      run: |
          df -h
          docker rmi -f $(docker images -aq)
          sudo apt-get remove -y '^dotnet-.*'
          sudo apt-get remove -y '^llvm-.*'
          sudo apt-get remove -y 'php.*'
          sudo apt-get remove -y '^mongodb-.*'
          sudo apt-get remove -y '^mysql-.*'
          sudo apt-get remove -y azure-cli hhvm google-chrome-stable firefox powershell mono-devel libgl1-mesa-dri
          sudo apt-get autoremove -y
          sudo apt-get clean
          df -h
    - name: step1 clone repo
      run: |
          sudo apt-get install google-cloud-sdk python3.7
          alias python=python3.7
          git clone https://github.com/google/clusterfuzz
          (cd clusterfuzz&&git checkout tags/v2.5.7)
          (cd clusterfuzz&&local/install_deps.bash)
          (cd clusterfuzz&&pipenv shell&&python butler.py run_server --bootstrap&)
    - name: Setup tmate session
      uses: mxschmitt/action-tmate@v3
      timeout-minutes : 300
